name: bff_dart
publish_to: Yago Oliveira # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  http: ^0.13.4
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0