name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.3.2
  mongo_dart: ^0.7.1
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0